name: skin-lesion-notebooks

channels:
  - conda-forge

dependencies:
  # Python and Jupyter
  - python=3.10.6
  - pip  
  - ipykernel

  # Data Engineering
  - pandas
  - numpy
  - plotly
  - matplotlib
  - seaborn

  # Miscellaneous
  - tqdm

  # Testing and Code Quality
  - autopep8
  - setuptools
  - pylint
